version: '3.8'
services:
  mysql_seim:
    image: mysql:latest
    container_name: sql_seim
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_DATABASE: seim
    ports:
      - '${ORM_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - seim-network
    env_file:
      - .env

  redis_seim:
    image: redis:latest
    container_name: redis_seim
    hostname: redis
    volumes:
      - /var/lib/redis
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - HOST=${REDIS_HOST}
    networks:
      - seim-network
    env_file:
      - .env

volumes:
  mysql_data:

networks:
  seim-network:
    external: true
