name: CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: run docker
        run: docker compose up -d

      - name: Run db migrations
        run: sudo chmod +x ./rundb.sh

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./dist/* ./package.json .env
          remote_path: /home/${{ secrets.EC2_USER }}/my-app-2/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: '${{ secrets.SSH_PRIVATE_KEY }}'

      - name: Test SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

      - name: Start Server
        run: |
          #  This is the private key used to connect to the server(key.pem in ec2)
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd /home/${{ secrets.EC2_USER }}/my-app-2
            npm install -f
            npm run build
            ./rundb.sh
            pm2 start dist/main.js --name test_app_2
            pm2 save
          '
