name: CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: run docker
        run: docker compose up -d

      - name: Run db migrations
        run: sudo chmod +x ./rundb.sh

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./* ./package.json .env
          remote_path: /home/${{ secrets.USER }}/my-app-2/
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER }}
          remote_password: ${{ secrets.PASSWORD }}

      - name: Test SSH Connection
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} 'echo "SSH connection successful"'

      - name: Start Server
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} '
            cd /home/${{ secrets.USER }}/my-app-2
            npm install -f
            npm run build
            ./rundb.sh
            pm2 start dist/main.js --name test_app_2
            pm2 save
          '
