name: CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Debug SSH_PRIVATE_KEY
        run: |
          echo "SSH_PRIVATE_KEY:"
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Test SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} 'echo "SSH connection successful"'

      - name: run docker
        run: docker compose up -d

      - name: Run db migrations
        run: sudo chmod +x ./rundb.sh

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # correct the directory path
            cd ~/app

            # Ensure the code is present (it's assumed it's a git repository
            git pull origin master
            git status

            # Install only production dependencies
            npm install -f --omit=dev

            # Build the application
            npm run build

            ls -la

            # Run database migrations
            sudo chmod +x rundb.sh
            ./rundb.sh

            # Start or restart the application with PM2
            pm2 startOrRestart dist/main.js --name test_app_2

            # Save the PM2 process list
            pm2 save
